twilio/calcite-kudu

adapter/pom.xml
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduRules.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduSortRule.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduSortedAggregationRule.java
adapter/src/test/java/com/twilio/kudu/sql/DescendingSortedOnDatetimeIT.java
adapter/src/test/java/com/twilio/kudu/sql/JDBCQueryIT.java
pom.xml

Summary:
These rules feel very tortured. This simplifies the operand a lot and
preps it for moving to a Converter rule.
It simplifies the operands and leverages the
`RelMetadataQuery#getAllPredicates` to surface up the filter
conditions. This should allow it to be more generic and applicable.
TODO:
Need to come back around to the sorted aggregation rule and adjust it
to use the new sort aggregation in kudu enumerable rules

Simplify sort rules to remove complex logic

---

adapter/src/main/java/com/twilio/kudu/sql/rules/KuduRules.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduSortRule.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduSortedAggregationRule.java
adapter/src/test/java/com/twilio/kudu/sql/DescendingSortedOnDatetimeIT.java
adapter/src/test/java/com/twilio/kudu/sql/JDBCQueryIT.java

Summary:
As noted in the last comment in this PR:
https://github.com/twilio/calcite-kudu/pull/2#issuecomment-754976144
The rule is failing to properly handle a Sort Over a Projection. When
Sort is over a Projection, the `sortField.getFieldIndex()` reflects
the field's position in the Projection and the code assumed it
reflected the field's position in the Kudu table.
This reverts commit bd9f9055a074afae0d940deaae8edaaad7c375b6, reversing
changes made to 0b44ba05eceaa238b94fcde6132c82244ed7ee7d.
This includes a new Test to show the issue and prevent future regressions.

Revert Sort Simplification

---

adapter/src/main/java/com/twilio/kudu/sql/rules/KuduSortRule.java
adapter/src/test/java/com/twilio/kudu/sql/DescendingSortedOnDatetimeIT.java
adapter/src/test/java/com/twilio/kudu/sql/PaginationIT.java

Summary:
Our internal integration tests identified a regression with
NestedLoopJoin. This Rel needs to be reworked to match
`org.apache.calcite.adapter.enumerable.EnumerableBatchNestedJoin`
instead of this current one. To avoid having to rework it completely
now, this commit fixes that regression and kicks the can down the road

Fix regression on Nested Join

---

pom.xml

Java8 compiled jars will allow lower versioned JVM repos to use code as well.
- [ YES ] I acknowledge that all my contributions will be made under the project's license.

Use java 8 when producing compiled jars

---

adapter/pom.xml
adapter/src/main/java/com/twilio/kudu/sql/CloneableEnumerable.java
adapter/src/main/java/com/twilio/kudu/sql/KuduEnumerable.java
adapter/src/main/java/com/twilio/kudu/sql/NestedJoinFactory.java
adapter/src/main/java/com/twilio/kudu/sql/TranslationPredicate.java
adapter/src/test/java/com/twilio/kudu/sql/NestedJoinCacheTest.java
pom.xml

Summary:
This implements a cache between the resulting Predicates when
executing a nested loop join.
Problem:
In a Nested Loop Join, the query is sending the same RPC requests over
and over again and fetching the same results. This makes the query
perform notably slower because of all the network traffic.
Solution:
This creates a fixed size `Map<Predicates, CachedResults>` that is
local to the current nested loop join context. Each `CachedResult`
maps to a set of predicates specific to the row on the left and
therefore shouldn't return thousands or millions of results -- it is
assumed the cached results will be small but not necessarily uniform
in size.
> All third-party contributors acknowledge that any contributions they provide will be made under the same …

Caching Nested Join implementation

---

adapter/src/main/java/com/twilio/kudu/sql/CalciteKuduEnumerable.java
adapter/src/main/java/com/twilio/kudu/sql/CalciteScannerMessage.java
adapter/src/test/java/com/twilio/kudu/sql/CalciteKuduEnumerableTest.java

Summary:
Awhile back this code was refactored and the `ScannerCallback` stopped
sending a `CLOSE` message right after an `ERROR` message. Frankly the
original behavior was silly as well. This changes that to close the
`Enumerator` whenever the message is `ERROR` or `CLOSE`
- [ X] I acknowledge that all my contributions will be made under the project's license.

Exit the Enumerable when scanner is in error state

---

adapter/src/main/java/com/twilio/kudu/sql/rules/KuduFilterRule.java

Summary:
In our service, we use `ROW` type to contain two values for our paging
design. This is not really supported by Calcite and causing
compilation errors when generating the query:
```
java.lang.RuntimeException: while resolving method 'gt[class [Ljava.lang.Object;, class
[Ljava.lang.Object;]' in class class org.apache.calcite.runtime.SqlFunctions
```
This is because the in memory filters include the original `ROW` type
instead of the expanded disjunction created by:
`RowValueExpressionConverter`

Use the deconstructed condition for filter rel

---

adapter/src/main/java/com/twilio/kudu/dataloader/DataLoader.java
adapter/src/test/java/com/twilio/kudu/sql/ScenarioIT.java

In case of mixed time granularity of cubes and using min amongst them for deciding on the number of threads, the time ranges are unique for the smallest time granularity cube but not for any cube having granularity greater than that.
Hence, rows get overwritten(upserted) in CubeMutationState from different threads for any cube bigger than the smallest granularity.
In order to keep uniqueness in thread splitting of rows to write, we need the max granularity rolled up time of a cube
- [Yes ] I acknowledge that all my contributions will be made under the project's license.

Use the max Cube granularity among the cubes

---

adapter/src/main/java/com/twilio/kudu/sql/rel/KuduNestedJoin.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduNestedJoinRule.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduRules.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduSortRule.java
adapter/src/test/java/com/twilio/kudu/sql/DescendingSortedOnDatetimeIT.java
adapter/src/test/java/com/twilio/kudu/sql/PaginationIT.java

Summary:
To support another physical trait, the sort rule can't be pinned to
`EnumerableConvention` trait.

Remove `KuduToEnumerableRel` from `KuduSortRule`s

---

adapter/src/main/java/com/twilio/kudu/sql/ScannerCallback.java

Looking a bit at query performance for a `null set` query I noticed
this code was calling out to the `AtomicBoolean#get()`. This uses a
votiale:
https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/lang/invoke/VarHandle.java#L579-L606
Which can be "expensive" to reference.
If the logger is configured at `DEBUG` level, then the logger will
call `AtomicBoolean#toString()` which in turn references the
`volatile` to render the String. So this doesn't change behavior if
the logger is `DEBUG` level but does prevent the `volatile` from being
dereferenced if logger is configured for `INFO` or higher.
> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source …

Reduce cost on every `CLOSE` message when logger is > DEBUG level

---

adapter/src/main/java/com/twilio/kudu/sql/KuduQuery.java
adapter/src/main/java/com/twilio/kudu/sql/SqlUtil.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduNestedJoinRule.java
adapter/src/main/java/org/apache/calcite/jdbc/KuduDriver.java
adapter/src/main/java/org/apache/calcite/prepare/KuduPrepareImpl.java
adapter/src/test/java/com/twilio/kudu/sql/ScenarioIT.java
adapter/src/test/resources/scenarios/ReportCenter.UsageReportTransactions.json

Add a hint that can be used to force a query to use KuduNestedJoin (by default the EnumerableHashJoin is used). 

Add USE_KUDU_NESTED_JOIN hint

---

adapter/src/main/java/com/twilio/kudu/sql/KuduQuery.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduRules.java

Working on a non-enumerable convention and would like to ensure the
Enumerable Rules are not enabled in that planner
Uses the `CalciteSystemProperty#ENABLE_ENUMERABLE` to check for
EnumerableRules that are being activated. This is used in
`RelOptUtil#registerDefaultRules` as well:
https://github.com/apache/calcite/blob/4bc916619fd286b2c0cc4d5c653c96a68801d74e/core/src/main/java/org/apache/calcite/plan/RelOptUtil.java#L2084-L2087

Add Enumerable Rules only when enumerable is enabled

---

adapter/src/main/java/com/twilio/kudu/sql/CalciteKuduTable.java
adapter/src/main/java/com/twilio/kudu/sql/KuduEnumerable.java
adapter/src/main/java/com/twilio/kudu/sql/KuduMethod.java
adapter/src/main/java/com/twilio/kudu/sql/KuduRelNode.java
adapter/src/main/java/com/twilio/kudu/sql/rel/KuduSortRel.java
adapter/src/main/java/com/twilio/kudu/sql/rel/KuduToEnumerableRel.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduAggregationLimitRule.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduRules.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduSortRule.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduSortedAggregationRule.java
adapter/src/test/java/com/twilio/kudu/sql/JDBCQueryIT.java
adapter/src/test/java/com/twilio/kudu/sql/KuduQueryIT.java
adapter/src/test/java/com/twilio/kudu/sql/SortedAggregationIT.java

Adds a new rule ` KuduAggregationLimitRule` that can be used to limit the number of rows read for a query that orders by a prefix of the primary key columns and other columns and group by only a prefix of the pk columns. 

Add KuduAggregationLimitRule

---

adapter/pom.xml
pom.xml

Log4j1.x has been end of life for a long while.
It was added as a test dependency so we could control the log output
during builds. I lazily added log4j that ships with slf4j -- which is
log4j1.x. After moving to log4j 2.15.0 implementation, we can see that
https://javalibs.com/artifact/com.google.uzaygezen/uzaygezen-core
brings in and old log4j library -- and it brings in an old apache
commons and guava. By specifying log4j as an `exclusion` it will not
be included into the dependencies.

log4j1.x removal

---

adapter/src/main/java/com/twilio/kudu/sql/KuduEnumerable.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduAggregationLimitRule.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduSortedAggregationRule.java
adapter/src/main/java/com/twilio/kudu/sql/schema/KuduSchema.java
adapter/src/test/java/com/twilio/kudu/sql/JDBCQueryIT.java
adapter/src/test/java/com/twilio/kudu/sql/SortedAggregationIT.java

Modify KuduAggregationLimitRule to not check that the GROUP BY columns are a prefix of the primary key so that we limit the amount of rows that have to be read from kudu if we sort by a prefix of the primary key. 
This PR also modified sortedEnumerator to use a minHeap to keep track of the smallest element from each of the scanners used to query kudu which speeds us queries.

Modify KuduAggregationLimitRule to not check that the GROUP BY columns are a prefix of the primary key

---

adapter/src/main/java/com/twilio/kudu/sql/CalciteKuduTable.java
adapter/src/main/java/com/twilio/kudu/sql/KuduEnumerable.java
adapter/src/main/java/com/twilio/kudu/sql/KuduMethod.java
adapter/src/main/java/com/twilio/kudu/sql/KuduRelNode.java
adapter/src/main/java/com/twilio/kudu/sql/rel/KuduToEnumerableRel.java
adapter/src/test/java/com/twilio/kudu/sql/KuduQueryIT.java

Add snapshot diff variable to configure how long back to look into the past per query. 
Essential for fault tolerant scanners to look inside replicas when leader tablets are not reachable and a new leader has not yet been elected. 
- [Y] I acknowledge that all my contributions will be made under the project's license.

Add snapshotDiffFromCurrentTime as parameter to KuduQuery method

---

adapter/src/main/java/com/twilio/kudu/sql/CalciteKuduTable.java
adapter/src/main/java/com/twilio/kudu/sql/KuduQuery.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduAggregationLimitRule.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduFilterRule.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduPredicatePushDownVisitor.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduSortRule.java
adapter/src/test/java/com/twilio/kudu/sql/PaginationIT.java
adapter/src/test/java/com/twilio/kudu/sql/rules/NumberFilterTest.java

Existing changes result in OR being applied to all IN clauses. Inorder to avoid that we 
1. Provide hint DISABLE_IN_LIST_OPTIMIZATION to use OR clause for IN queries needed for Org queries
2. Verified locally KJ test OutboundMessagesIT and OrganizationPaginationIT pass after these changes

Use DISABLE_IN_LIST_OPTIMIZATION to use OR clause for IN queries

---

adapter/src/main/java/com/twilio/kudu/sql/CalciteKuduTable.java
adapter/src/main/java/com/twilio/kudu/sql/CalciteKuduTableBuilder.java
adapter/src/main/java/com/twilio/kudu/sql/CalciteModifiableKuduTable.java
adapter/src/main/java/com/twilio/kudu/sql/KuduEnumerable.java
adapter/src/main/java/com/twilio/kudu/sql/KuduMethod.java
adapter/src/main/java/com/twilio/kudu/sql/KuduRelNode.java
adapter/src/main/java/com/twilio/kudu/sql/rel/KuduToEnumerableRel.java
adapter/src/main/java/com/twilio/kudu/sql/schema/KuduSchema.java
adapter/src/test/java/com/twilio/kudu/sql/KuduQueryIT.java

Adding read snapshot difference property to KuduSchema to allow it being set through JDBC url or through KuduSchemaFactory for each CalciteKuduTable
- [Y ] I acknowledge that all my contributions will be made under the project's license.

Revert snapshotDiff changes and add property to KuduSchema

---

adapter/src/main/java/com/twilio/kudu/sql/KuduRelNode.java
adapter/src/main/java/com/twilio/kudu/sql/rel/KuduSortRel.java

Create a copy of the objects used for setting `sortPkPrefixColumns` and `sortPkColumns` in KuduImplementor. We have seen errors that might point to this being a bug.
```
Caused by: java.lang.IllegalStateException: Unable to find primary key column event_date in the projection.
at com.twilio.kudu.sql.CalciteKuduTable.getPrimaryKeyColumnsInProjection(CalciteKuduTable.java:413)
at com.twilio.kudu.sql.ScannerCallback.<init>(ScannerCallback.java:75)
at com.twilio.kudu.sql.KuduEnumerable.lambda$enumerator$0(KuduEnumerable.java:410)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at …
```

Fix bug in KuduImplementor sortPkColumns usage.

---

pom.xml

`calcite-core` pulls in 2.4 which was released in 2012. Versions less
than 2.7 allow strings to traverse into the parent directories.
https://security.snyk.io/vuln/SNYK-JAVA-COMMONSIO-1277109
Adds a comment around the `calcite.version` property to help the
engineer check the calcite bug to see if it is addressed.
It adds `commons-io` dependency into the `dependencyManagement`
section so that it is used whenever `commons-io` is pulled into a
module.
We can see this works:
```
mvn dependency:tree | grep commons-io
[INFO] |  +- commons-io:commons-io:jar:2.11.0:runtime
```

Set commons-io to 2.11.0 to address CVE-2021-29425

---

adapter/src/main/java/com/twilio/kudu/sql/CalciteKuduTable.java
adapter/src/main/java/com/twilio/kudu/sql/KuduEnumerable.java
adapter/src/main/java/com/twilio/kudu/sql/KuduRelNode.java
adapter/src/main/java/com/twilio/kudu/sql/ScannerCallback.java
adapter/src/main/java/com/twilio/kudu/sql/rel/KuduSortRel.java
adapter/src/main/java/com/twilio/kudu/sql/rel/KuduToEnumerableRel.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduAggregationLimitRule.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduSortRule.java
adapter/src/main/java/com/twilio/kudu/sql/rules/KuduSortedAggregationRule.java
adapter/src/test/java/com/twilio/kudu/sql/DescendingSortedOnDatetimeIT.java
adapter/src/test/java/com/twilio/kudu/sql/PaginationIT.java
adapter/src/test/java/com/twilio/kudu/sql/SortedTest.java

Generates the `sortPkColumns` in `KuduToEnumerableRel` and passes it to executeQuery as a List<Integer>.
Also modify the KuduSortRule to get matches if the query has an OFFSET, previously the sort was pushed down but the rule wasn't matched. 

 Fix bug in KuduImplementor sortPkColumns usage

---

adapter/src/main/java/com/twilio/kudu/sql/rules/KuduSortedAggregationRule.java
adapter/src/test/java/com/twilio/kudu/sql/SortedAggregationIT.java

`remappingOrdinals` does not need to be mapped through the group by fields as these refer to the projected columns. 
`testKuduSortedAggregationRuleNotMatched` fails without this fix
```
Caused by: java.lang.RuntimeException: Error while applying rule KuduSortedAggregationRule, args [rel#127:EnumerableLimitSort.ENUMERABLE.[1, 0](input=RelSubset#122,sort0=$1,sort1=$0,dir0=ASC,dir1=ASC,fetch=30), rel#121:EnumerableAggregate.ENUMERABLE.[](input=RelSubset#116,group={0},MY_SUM=SUM($1)), rel#141:KuduToEnumerableRel.ENUMERABLE.[](input=RelSubset#119), rel#159:KuduProjectRel.KUDU.[](input=RelSubset#133,exprs=[$4, $3]), rel#132:KuduFilterRel.KUDU.[](input=RelSubset#84,ScanToken 1=ACCOUNT_SID EQUAL ACCOUNT1), rel#57:KuduQuery.KUDU.[](table=[kudu, SortedAggregationIT])]
at …
```

Fix bug in KuduSortedAggregationRule

---

pom.xml

This got flagged by depend bot:
https://github.com/advisories/GHSA-57j2-w4cx-62h2
This removes the previous code that pulls in specific artifacts and
uses the Jackson bill of materials project:
https://github.com/FasterXML/jackson-bom
The `<scope>import</scope>` then imports the various jackson
artifacts with the proper versions

Update jackson to address deeply nested stack overflow attack

---

adapter/pom.xml
adapter/src/main/java/com/twilio/kudu/sql/rel/KuduToEnumerableRel.java
adapter/src/test/java/com/twilio/kudu/sql/SortedTest.java
pom.xml

Fix for intermittent failures of not finding sort Indexes in current thread/query's list suggesting a leak - 
```bash
Suppressed: java.lang.IllegalStateException: Unable to find primary key column index 1 in the projection, projectedColumnIndices 2, 5, 6 sortPkColumnIndices 1
at com.twilio.kudu.sql.rel.KuduToEnumerableRel.getPrimaryKeyColumnsInProjection(KuduToEnumerableRel.java:292)
at com.twilio.kudu.sql.rel.KuduToEnumerableRel.executeQuery(KuduToEnumerableRel.java:231)
at com.twilio.kudu.sql.rel.KuduToEnumerableRel.implement(KuduToEnumerableRel.java:89)
at org.apache.calcite.adapter.enumerable.EnumerableRelImplementor.implementRoot(EnumerableRelImplementor.java:108)
... 6 more 
```
> All third-party contributors acknowledge that any contributions they provide …

Remove static references

---

adapter/src/test/java/com/twilio/kudu/sql/parser/KuduDDLIT.java
pom.xml

Bump up kudu-client version to 1.16.0 
Remove undefined properties from DDL SQLs as KuduClient now throws a `NonRecoverableException` on unknown extra configs

Bump up kudu version to 1.16.0

---

pom.xml

commons-dpcp2 used to leak password information over jmx. This causes
Synk to flag it as a problem.
Looking at the other fixes, after bumping to calcite 1.31.0, we can
remove the json smart, httpcomponents and jackson changes
Adds a commons-dpcp2 to dependency management with the latest
version. This ensure calcite doesn't pull down the vulnerable
one. Added a links for the resolution and added a note about above
calcite version to remind us to clean this mess up once resolved in
calcite.

Fix commons-dpcp2 vuln and clean up other vuln fixes

---

adapter/src/main/java/com/twilio/kudu/sql/KuduQuery.java

As noted here https://github.com/apache/calcite/pull/2975, the rule doesn't pass the field aliases into the new project it creates. This breaks the result set.
By removing the rule from the planner when the `KuduQuery` is registered with the planner and cluster

Remove the new Semi Join Rule because it drops Project aliases

---

adapter/src/main/java/com/twilio/kudu/sql/KuduQuery.java

After working on CALCITE-5391, I came to the conclusion the rule is not actually broken -- not strictly -- and Twilio's own application is actually not using Calcite correctly. As discovered by Drill and Twilio, Calcite's planner will accept a new `RelNode` from a rule that matches the shape of the original *but doesn't have the same names*. This allows for different optimizations within the planner.
To use Calcite correctly, the applications need to keep the original validated type from before the physical planning. This can be seen in how the JDBC uses RelRoot.
Removes the removed rule

Re-enable Unique Semi Join rule

---

adapter/src/main/codegen/config.fmpp
pom.xml

To keep pace with changes and improvements with within Calcite.
[Calcite fixes the log4j1 that was being pulled in by uzaygezen-core](https://issues.apache.org/jira/browse/CALCITE-4858). The commons codec has a bunch of improvements as well.

Calcite 1.34 and Commons Codec 1.15

---

.github/workflows/publish-release.yml
.github/workflows/run-code-format.yml
.github/workflows/run-tests.yml
.travis.yml
adapter/pom.xml
adapter/src/main/java/org/apache/calcite/prepare/KuduPrepareImpl.java
cli/Dockerfile
pom.xml

Move from using JDK8 to JDK17, because at the moment projects that have `calcite-kudu` as a dependency fail to build on JDK17.

Build on JDK17

---

pom.xml

Maven Central deploys are failing after the JDK 17 migration. Bumping this plugin version should fix it.
https://stackoverflow.com/questions/70153962/nexus-staging-maven-plugin-maven-deploy-failed-an-api-incompatibility-was-enco

Bump nexus-staging-maven-plugin from 1.6.8 to 1.6.13

---

adapter/pom.xml
adapter/src/main/codegen/config.fmpp
adapter/src/main/java/com/twilio/kudu/sql/KuduPhysType.java
adapter/src/main/java/com/twilio/kudu/sql/schema/KuduSchema.java
pom.xml

- Bump up plugin versions
- Bump up calcite version
- Bump up kudu version
- Upserts would fail with exception - 
```bash
Caused by: java.sql.SQLException: Error while preparing statement [UPSERT INTO "X" (.........) VALUES (..........)]
at org.apache.calcite.avatica.Helper.createException(Helper.java:56)
at org.apache.calcite.avatica.Helper.createException(Helper.java:41)
at org.apache.calcite.jdbc.CalciteConnectionImpl.prepareStatement_(CalciteConnectionImpl.java:226)
at org.apache.calcite.jdbc.CalciteConnectionImpl.prepareStatement(CalciteConnectionImpl.java:205)
at org.apache.calcite.jdbc.KuduCalciteConnectionImpl.prepareStatement(KuduCalciteConnectionImpl.java:22)
at org.apache.calcite.jdbc.CalciteConnectionImpl.prepareStatement(CalciteConnectionImpl.java:101)
at …
```

Bump up calcite version and make upsert using materializedView threadsafe
